<div id="main">
<h1>Edit my password </h1>

<form method="post" action="/profile/editpassword" onsubmit="return validateEditPassword();">
    <table>
        <tr>
            <td></td>
            <td><div id="messageEdit"></div></td>
        </tr>

        <tr>
            <td><label for="password1">New password :</label></td>
            <td><input type="password" name="password1Edit" id="password1Edit" value="" size="39" maxlength="30"></td>
        </tr>

        <tr>
            <td><label for="password2">Confirm password :</label></td>
            <td><input type="password" name="password2Edit" id="password2Edit" value="" size="39" maxlength="30"></td>
        </tr>

        <tr>
            <td></td>
            <td><button id="submit" type="submit">Save</button></td>
        </tr>
    </table>
</form>