<div id="main">


    <iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=fr&amp;geocode=&amp;q=ECE+Paris+Ecole+d'Ing%C3%A9nieurs,+Quai+de+Grenelle,+Paris,+France&amp;aq=3&amp;oq=ece+paris&amp;sll=37.0625,-95.677068&amp;sspn=46.005754,93.076172&amp;t=h&amp;ie=UTF8&amp;hq=ECE+Paris+Ecole+d'Ing%C3%A9nieurs,+Quai+de+Grenelle,+Paris,+France&amp;z=14&amp;iwloc=A&amp;cid=12353337026704731612&amp;ll=48.852035,2.285981&amp;output=embed">
    
    </iframe>
  
 
    <div id="contact-text">Pierre Ghazal / Robin Joganah / Julien Fabre </div>
