<div id="main-jcarousel-whoarewe">
    <script
src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDY0kkJiTPVd2U7aTOAwhc9ySH6oHxOIYM&sensor=false">
</script>

<script>
function initialize()
{
var mapProp = {
  center:new google.maps.LatLng(51.508742,-0.120850),
  zoom:5,
  mapTypeId:google.maps.MapTypeId.ROADMAP
  };
var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);
}

google.maps.event.addDomListener(window, 'load', initialize);
</script>
<div class="jcarousel-whoarewe">

    <img src="/script/img/david1.jpg" width="958" height="500" alt="">
    <img src="/script/img/david2.jpeg" width="958" height="500" alt="">
    <img src="/script/img/david3.jpg" width="958" height="500" alt="">
    
</div>

<script type="text/javascript">
    $(function() {
        $(document).ready(function() {
            $('.jcarousel-whoarewe').cycle({
                fx: 'fade', // choose your transition type, ex: fade, scrollUp, shuffle, etc...
                speed: 2000,
                timeout:2500
            });


        });
    });
</script>

